version: 0.0
Resources:
  - lambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: your-lambda-function-name
        Alias: live
        CurrentVersion:
          Fn::GetAtt:
            - lambdaFunction
            - Version
