version: 0.0
Resources:
  - lambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: my-real-lambda-function-name  # <-- put your actual function name here
        Alias: live                         # <-- this alias MUST already exist
        CurrentVersion:
          Fn::GetAtt:
            - lambdaFunction
            - Version
